In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('D:\\Internship\\dataset\\data.csv')

In [5]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0  100.668411         1   68          1           1              1
1   99.797366         1   63          0           1              1
2   99.854867         1   49          1           0              1
3   98.486518         1   24          1          -1              1
4  100.723072         1   29          1           1              0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2186 entries, 0 to 2185
Data columns (total 6 columns):
fever            2186 non-null float64
bodyPain         2186 non-null int64
age              2186 non-null int64
runnyNose        2186 non-null int64
diffBreath       2186 non-null int64
infectionProb    2186 non-null int64
dtypes: float64(1), int64(5)
memory usage: 102.5 KB


In [7]:
df['runnyNose'].value_counts()

1    1103
0    1083
Name: runnyNose, dtype: int64

In [8]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  \
count  2186.000000  2186.000000  2186.000000  2186.000000  2186.000000   
mean    100.004803     0.489478    35.380146     0.504575     0.016926   
std       1.151609     0.500004    20.471078     0.500093     0.823114   
min      98.000834     0.000000     1.000000     0.000000    -1.000000   
25%      99.019113     0.000000    17.000000     0.000000    -1.000000   
50%      99.989214     0.000000    36.000000     1.000000     0.000000   
75%     101.005034     1.000000    53.000000     1.000000     1.000000   
max     101.999814     1.000000    70.000000     1.000000     1.000000   

       infectionProb  
count    2186.000000  
mean        0.514181  
std         0.499913  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

In [9]:
import numpy as np

In [10]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data)*ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]


In [11]:
train, test = data_split(df, 0.2)

In [12]:
train[:10]

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
859    99.760241         1   60          1           0              0
637   100.251682         1   16          0           1              0
478   101.368908         1   34          1          -1              0
256    98.472039         0   25          1          -1              1
1486   99.252237         0   30          0          -1              0
440    99.437466         1   36          0           0              1
561   101.977448         1   36          0           0              0
2116  101.766672         0   40          0           1              0
479    99.283214         0   37          0           1              0
1000  101.092695         0   19          1          -1              0
596    98.934552         0   60          0          -1              1
1258  100.843649         1   22          1          -1              1
20    101.699689         1   40          1           1              0
1170  101.486611         0   60          0           0              1
636   101.006481         1    6          1           1              0
1771  100.430731         0   17          1          -1              1
381   101.605854         1   38          0          -1              1
1264  100.619184         0    7          0           1              1
1404   98.951774         0   27          0           0              0
1481   99.106140         1   27          0           0              1
1483  100.801505         1    9          0           0              0
2077  101.221350         1   66          1           1              1
889    98.882046         0    7          1           0              1
809    99.581618         0   69          0           1              0
1259   99.339324         1   51          0          -1              1
2136  101.485200         0    7          1           0              0
1864   98.348237         0   23          0           0              0
1106  101.989856         1   46          0          -1              1
1543  101.891323         0   50          1          -1              1
374   100.888781         1   44          0           0              1
...          ...       ...  ...        ...         ...            ...
1267   98.891177         1   41          1           0              1
1899  101.757286         1   67          0           1              0
562   101.880501         0   50          0           0              1
189    99.315337         1   62          0          -1              1
1806   99.380834         0   68          1           0              1
975   100.964487         0   58          0           1              1
2047  100.271323         0   68          1           0              0
1082  100.429067         0   25          1          -1              1
474    98.721193         0   54          0          -1              1
747    99.332061         0   17          1           0              1
21    101.215235         0   31          1           1              0
459   101.568688         1   31          1           1              0
1184   98.456813         0   11          1           1              0
955    98.406370         1   50          0           0              0
1215   98.192521         1   40          1           1              0
1515  101.841571         1   22          1           1              1
769    98.857794         1   47          1           0              1
1685   98.025037         1   30          0           0              0
130    99.631392         0   56          1          -1              1
2135  101.558469         1   61          1          -1              0
1482   99.072807         0   11          0           1              0
330    98.920277         0   69          0           0              1
1238   99.407673         1   57          0          -1              1
466   100.890494         0   33          1           0              0
2169   99.242968         1   26          0          -1              0
1638  100.734806     

In [13]:
test[:10]

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
741    99.514573         1   49          1           1              0
1315  101.583880         0   33          1          -1              0
2051   99.111746         1   59          0           1              0
930   100.448537         0   52          0           1              0
1476   99.463685         0   42          1           0              1
1837   98.274013         0   50          0          -1              0
771   101.659145         0   24          0           1              1
1735   98.385879         1   38          1           1              1
1541  101.530206         0   41          1           1              0
567   101.539279         1   19          1          -1              0
892    99.068892         0   62          0          -1              0
1465  101.846998         1   10          1           0              1
1786  101.464718         1   66          0           0              1
1055  101.381352         0    3          1           0              1
109    99.158763         0   15          0          -1              0
211    99.138740         1   44          1           1              0
409   100.424657         1   53          1           1              1
1573  100.041105         0    2          0          -1              0
29    101.860681         0   68          0           0              1
410    98.185528         0   20          0          -1              0
1225  100.823287         1   18          0           1              1
1669   98.510333         0   62          1           1              0
259    98.207286         0   70          1          -1              1
2034   98.921663         1   12          1          -1              1
1182   98.207789         0   60          1          -1              1
168    99.987504         0   32          1           1              1
2177   99.666049         1   59          1          -1              0
1909  101.146794         1   25          1           0              1
1366   98.527986         1   49          0           1              1
383    99.818301         0   70          1          -1              0
...          ...       ...  ...        ...         ...            ...
1929   99.249437         0   25          0          -1              0
414    98.796349         0   22          0          -1              1
831   100.721423         1   44          1          -1              1
810   101.244164         0   70          1           1              1
23    101.542010         1    9          0          -1              1
1838  100.954046         0   33          0           0              0
1844  101.647163         0   70          1           1              0
1009   98.292546         1   58          0           0              0
198    98.068626         1   47          0           1              1
49     99.519484         1    2          1          -1              0
173   100.751916         0   62          0          -1              0
426   101.048026         1   16          1           0              0
482    98.403957         0   41          1           0              0
943   100.872803         0   24          1           0              0
308    99.641384         1   58          1           1              0
1293  101.193947         0    3          0           1              0
1711  101.703177         1   54          1           0              1
59    101.399157         0   30          1          -1              0
71    101.627575         0   15          0           0              0
1456   98.237255         0   22          0           1              1
1931   98.156576         1   68          0          -1              0
1192   99.853854         1    1          0           0              0
668   100.262568         0   63          0          -1              0
1387   98.794420         1   64          1           1              1
873   100.582608         0   55          1           0              0
857    98.853471     

In [21]:
X_train = train[['fever','bodyPain','age', 'runnyNose', 'diffBreath']].to_numpy()
X_test = test[['fever','bodyPain','age', 'runnyNose', 'diffBreath']].to_numpy()
X_test

array([[ 99.51457315,   1.        ,  49.        ,   1.        ,
          1.        ],
       [101.5838797 ,   0.        ,  33.        ,   1.        ,
         -1.        ],
       [ 99.11174626,   1.        ,  59.        ,   0.        ,
          1.        ],
       ...,
       [100.0685961 ,   0.        ,  68.        ,   1.        ,
          1.        ],
       [100.0270551 ,   1.        ,  43.        ,   0.        ,
          0.        ],
       [101.5093665 ,   1.        ,  68.        ,   0.        ,
         -1.        ]])

In [15]:
Y_train = train[['infectionProb']].to_numpy().reshape(1749,)
Y_test = test[['infectionProb']].to_numpy().reshape(437,)

In [16]:
Y_train

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

C:\Program Files\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
predictions = clf.predict(X_test)
print(predictions[:10])
Y_test[:10]

[0 1 0 0 1 1 1 0 1 1]


array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0], dtype=int64)

In [19]:
clf.predict([[100,1,22,1,1]])

array([1], dtype=int64)

In [23]:
inputfeatures = [99.85486676,1,49,1,0]
infProba = clf.predict_proba([inputfeatures])
infProba

array([[0.49523872, 0.50476128]])