In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [28]:
df = pd.read_csv('Cleaned.csv')
df[:5]

Age Gender Severity    Contact  Infected  Fever  Tiredness  Dry-Cough  \
0  0-9   Male     Mild        Yes       1.0      1          1          1   
1  0-9   Male     Mild        Yes       0.0      1          1          1   
2  0-9   Male     Mild         No       1.0      1          1          1   
3  0-9   Male     Mild         No       0.0      1          1          1   
4  0-9   Male     Mild  Dont-Know       1.0      1          1          1   

   Difficulty-in-Breathing  Sore-Throat  None_Sympton  Pains  \
0                        1            1             0      1   
1                        1            1             0      1   
2                        1            1             0      1   
3                        1            1             0      1   
4                        1            1             0      1   

   Nasal-Congestion  Runny-Nose  Diarrhea  None_Experiencing  
0                 1           1         1                  0  
1                 1           1         1                  0  
2                 1           1         1                  0  
3                 1           1         1                  0  
4                 1           1         1                  0

In [29]:
df.shape

(633600, 16)

In [30]:
df.describe()

Infected          Fever  Tiredness      Dry-Cough  \
count  633600.0  633600.000000   633600.0  633600.000000   
mean        0.5       0.312500        0.5       0.562500   
std         0.5       0.463513        0.5       0.496079   
min         0.0       0.000000        0.0       0.000000   
25%         0.0       0.000000        0.0       0.000000   
50%         0.5       0.000000        0.5       1.000000   
75%         1.0       1.000000        1.0       1.000000   
max         1.0       1.000000        1.0       1.000000   

       Difficulty-in-Breathing    Sore-Throat   None_Sympton          Pains  \
count                 633600.0  633600.000000  633600.000000  633600.000000   
mean                       0.5       0.312500       0.062500       0.363636   
std                        0.5       0.463513       0.242062       0.481046   
min                        0.0       0.000000       0.000000       0.000000   
25%                        0.0       0.000000       0.000000       0.000000   
50%                        0.5       0.000000       0.000000       0.000000   
75%                        1.0       1.000000       0.000000       1.000000   
max                        1.0       1.000000       1.000000       1.000000   

       Nasal-Congestion     Runny-Nose       Diarrhea  None_Experiencing  
count     633600.000000  633600.000000  633600.000000      633600.000000  
mean           0.545455       0.545455       0.363636           0.090909  
std            0.497930       0.497930       0.481046           0.287480  
min            0.000000       0.000000       0.000000           0.000000  
25%            0.000000       0.000000       0.000000           0.000000  
50%            1.000000       1.000000       0.000000           0.000000  
75%            1.000000       1.000000       1.000000           0.000000  
max            1.000000       1.000000       1.000000           1.000000

In [31]:
labels = np.array(df['Infected'])
labels[:5]

array([1., 0., 1., 0., 1.])

In [40]:
feature = df.drop(['Infected','Contact','Severity','Gender','Age'], axis=1)
# feature = df.drop('age', axis=1)
# print(feature[:10])
feature = np.array(feature)
print(feature.shape)
feature[:5]


(633600, 11)


array([[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0]], dtype=int64)

In [41]:
rf = RandomForestRegressor(n_estimators= 100, random_state = 42)

In [42]:
X_train, X_test, y_train, y_test = train_test_split(feature, labels, test_size=0.2, random_state=50)

In [43]:
print("Training data Size: ", X_train.shape)
print("Test data Sie: ", X_test.shape)

Training data Size:  (506880, 11)
Test data Sie:  (126720, 11)


In [44]:
rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=False, random_state=42, verbose=0,
                      warm_start=False)

In [45]:
prediction = rf.predict(X_test)
prediction[:10]


array([0.49671659, 0.49881056, 0.49227325, 0.50145841, 0.50079588,
       0.50583843, 0.5019202 , 0.49628965, 0.49253049, 0.49961862])

In [46]:
print("Actual Value: ", y_test[:10])
print("Predicted Value: ", prediction[:10])

Actual Value:  [0. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
Predicted Value:  [0.49671659 0.49881056 0.49227325 0.50145841 0.50079588 0.50583843
 0.5019202  0.49628965 0.49253049 0.49961862]


In [52]:
predictions = rf.predict([[1,0,1,0,1,1,1,0,1,1,1]])
predictions * 100

array([50.34896907])