In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_excel('D://Internship//dataset//COVID-19.xlsx')
df[:5]

Sno  age  gender  body temperature  Dry Cough  sour throat  weakness  \
0    1   20       1              98.6          0            0         0   
1    2   19       1              99.0          1            0         0   
2    3   55       0             102.0          1            1         1   
3    4   40       0             100.0          0            0         0   
4    5   33       1              99.2          0            1         0   

   breathing problem  drowsiness  pain in chest  ...  diabetes  heart disease  \
0                  0           0              0  ...         0              0   
1                  0           0              0  ...         0              0   
2                  1           1              1  ...         0              0   
3                  0           1              1  ...         1              0   
4                  1           0              0  ...         0              0   

   lung disease  stroke or reduced immunity  symptoms progressed  \
0             0                           0                    0   
1             0                           0                    0   
2             0                           0                    0   
3             0                           0                    1   
4             1                           1                    1   

   high blood pressue  kidney disease  change in appetide  \
0                   0               0                   0   
1                   0               0                   0   
2                   0               0                   1   
3                   1               0                   1   
4                   0               0                   0   

   Loss of sense of smell  Corona result  
0                       0              0  
1                       0              0  
2                       0              1  
3                       0              2  
4                       1              2  

[5 rows x 21 columns]

In [4]:
df.shape

(127, 21)

In [5]:
df.describe()

Sno         age      gender  body temperature   Dry Cough  \
count  127.000000  127.000000  127.000000        127.000000  127.000000   
mean    64.000000   36.456693    0.527559        100.031496    0.488189   
std     36.805797   14.052484    0.501217          1.569536    0.501840   
min      1.000000   18.000000    0.000000         96.000000    0.000000   
25%     32.500000   25.500000    0.000000         98.900000    0.000000   
50%     64.000000   33.000000    1.000000         99.700000    0.000000   
75%     95.500000   45.000000    1.000000        101.400000    1.000000   
max    127.000000   80.000000    1.000000        103.100000    1.000000   

       sour throat    weakness  breathing problem  drowsiness  pain in chest  \
count   127.000000  127.000000         127.000000  127.000000     127.000000   
mean      0.551181    0.409449           0.433071    0.425197       0.370079   
std       0.499343    0.493680           0.497463    0.496331       0.484738   
min       0.000000    0.000000           0.000000    0.000000       0.000000   
25%       0.000000    0.000000           0.000000    0.000000       0.000000   
50%       1.000000    0.000000           0.000000    0.000000       0.000000   
75%       1.000000    1.000000           1.000000    1.000000       1.000000   
max       1.000000    1.000000           1.000000    1.000000       1.000000   

       ...    diabetes  heart disease  lung disease  \
count  ...  127.000000     127.000000    127.000000   
mean   ...    0.244094       0.094488      0.141732   
std    ...    0.431250       0.293665      0.350157   
min    ...    0.000000       0.000000      0.000000   
25%    ...    0.000000       0.000000      0.000000   
50%    ...    0.000000       0.000000      0.000000   
75%    ...    0.000000       0.000000      0.000000   
max    ...    1.000000       1.000000      1.000000   

       stroke or reduced immunity  symptoms progressed  high blood pressue  \
count                  127.000000           127.000000          127.000000   
mean                     0.165354             0.480315            0.283465   
std                      0.372971             0.501591            0.452465   
min                      0.000000             0.000000            0.000000   
25%                      0.000000             0.000000            0.000000   
50%                      0.000000             0.000000            0.000000   
75%                      0.000000             1.000000            1.000000   
max                      1.000000             1.000000            1.000000   

       kidney disease  change in appetide  Loss of sense of smell  \
count      127.000000          127.000000              127.000000   
mean         0.133858            0.401575                0.448819   
std          0.341848            0.492158                0.499343   
min          0.000000            0.000000                0.000000   
25%          0.000000            0.000000                0.000000   
50%          0.000000            0.000000                0.000000   
75%          0.000000            1.000000                1.000000   
max          1.000000            1.000000                1.000000   

       Corona result  
count     127.000000  
mean        0.937008  
std         0.675513  
min         0.000000  
25%         0.000000  
50%         1.000000  
75%         1.000000  
max         2.000000  

[8 rows x 21 columns]

In [6]:
labels = np.array(df['Corona result'])
labels[:5]

array([0, 0, 1, 2, 2], dtype=int64)

In [7]:
feature = df.drop(['Corona result','Sno', 'stroke or reduced immunity','Loss of sense of smell',
                   'diabetes', 'heart disease', 'kidney disease','lung disease'], axis=1)
# print(feature.describe())
feature[:5]

age  gender  body temperature  Dry Cough  sour throat  weakness  \
0   20       1              98.6          0            0         0   
1   19       1              99.0          1            0         0   
2   55       0             102.0          1            1         1   
3   40       0             100.0          0            0         0   
4   33       1              99.2          0            1         0   

   breathing problem  drowsiness  pain in chest  \
0                  0           0              0   
1                  0           0              0   
2                  1           1              1   
3                  0           1              1   
4                  1           0              0   

   travel history to infected countries  symptoms progressed  \
0                                     0                    0   
1                                     0                    0   
2                                     0                    0   
3                                     1                    1   
4                                     1                    1   

   high blood pressue  change in appetide  
0                   0                   0  
1                   0                   0  
2                   0                   1  
3                   1                   1  
4                   0                   0

In [8]:
feature = np.array(feature)
feature.shape

(127, 13)

In [9]:
rf = RandomForestClassifier(n_estimators= 1000, random_state = 42)

In [10]:
X_train, X_test, y_train, y_test = train_test_split(feature, labels, test_size=0.2, random_state=30)

In [11]:
print("Training data Size: ", X_train.shape)
print("Test data Sie: ", X_test.shape)

Training data Size:  (101, 13)
Test data Sie:  (26, 13)


In [12]:
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [13]:
prediction = rf.predict(X_test)
prediction[:10]

array([0, 0, 1, 1, 2, 0, 1, 0, 1, 0], dtype=int64)

In [14]:
print("Actual Value:    ", y_test)
print("Predicted Value: ", prediction)

Actual Value:     [0 0 1 1 2 0 1 0 1 0 2 1 0 1 1 1 0 2 1 0 1 1 1 1 1 0]
Predicted Value:  [0 0 1 1 2 0 1 0 1 0 2 1 0 1 1 1 0 1 1 0 2 1 1 2 1 1]


In [15]:
acc = accuracy_score(prediction, y_test)
acc

0.8461538461538461

In [18]:
pred = rf.predict([[15,1,102.0,1,1,1,1,1,1,0,1,0,1]])
pred * 100

array([100], dtype=int64)

In [20]:
pred = rf.predict_proba([[15,1,102.0,1,1,1,1,1,1,0,1,0,1]])
predic = pred[0][1] + pred[0][2]
predic

0.831

In [21]:
# import pickle 
# file = open('RF148.pkl','wb')
# pickle.dump(rf, file)
# file.close()

In [22]:
# import pickle
# file = open('D:\\Internship\\Home\\static\\Models\\RF148.pkl','rb')
# clf = pickle.load(file)
# file.close()

In [24]:
# pred = clf.predict_proba([[15,1,102.0,1,1,1,1,1,1,0,1,0,1]])
# predic = pred[0][1] + pred[0][2]
# predic

0.831