In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
import  numpy as np

In [16]:
df = pd.read_csv('dataset\\symptoms.csv')
df

Dry Cough  High Fever  Sore Throat  Difficulty in breathing  \
0           0           2            3                        0   
1          15          15           20                       16   
2           4           5            0                        0   
3           4           7            9                       10   
4           0           0            1                        0   
5           6           0            6                        0   
6          16          17           18                       16   
7          17          17            0                        0   
8           0          18            0                       18   
9          16          15           18                       20   
10          0           8            0                        0   
11          7           8           10                        0   
12          8           0            6                       10   
13         15          17            0                       18   
14          2           5            0                        0   
15          5           0            1                        0   
16          0          18           17                       13   
17         17          18            0                        8   
18          0          15            0                       16   
19          7          18           12                       17   
20          0           3            8                        0   
21         20          16            0                        0   
22         16           0            0                       19   
23          0           0            1                        0   
24         17           0            0                        0   
25          0          10           16                       18   
26          6           8            0                        0   
27         14          16           17                        0   
28         15           0            0                        0   
29         20           0           18                        0   
30          0          20           19                        0   
31          8           8            0                        1   
32         10           8            2                        0   
33         12           0           18                        0   
34         17          19           20                        0   
35         12           0            0                        3   
36         20          16            0                        2   
37         16           4            0                       17   
38          1           0            2                        0   
39         14          20           16                        0   
40          0           8            0                        0   
41         19           0           20                        6   
42         18           0           15                        2   
43          0          10            0                        0   
44         20          20           20                       20   
45          0           5            5                        5   
46          6           0            6                        0   
47         19           0           19                       19   

    Infected with Covid19  
0                       0  
1                       1  
2                       0  
3                       0  
4                       0  
5                       0  
6                       1  
7                       1  
8                       1  
9                       1  
10                      0  
11                      0  
12                      0  
13                      1  
14                      0  
15                      0  
16                      1  
17                      1  
18                      1  
19                      1  
20                      0  
21                      1  
22                      1  
23                      0  
24                  

In [20]:
df.head()

Dry Cough  High Fever  Sore Throat  Difficulty in breathing  \
0          0           2            3                        0   
1         15          15           20                       16   
2          4           5            0                        0   
3          4           7            9                       10   
4          0           0            1                        0   

   Infected with Covid19  
0                      0  
1                      1  
2                      0  
3                      0  
4                      0

In [21]:
df.describe()

Dry Cough  High Fever  Sore Throat  Difficulty in breathing  \
count  48.000000   48.000000    48.000000                48.000000   
mean    9.145833    8.208333     7.145833                 5.708333   
std     7.525813    7.537024     8.021221                 7.701777   
min     0.000000    0.000000     0.000000                 0.000000   
25%     0.000000    0.000000     0.000000                 0.000000   
50%     8.000000    8.000000     2.500000                 0.000000   
75%    16.000000   16.000000    16.250000                13.750000   
max    20.000000   20.000000    20.000000                20.000000   

       Infected with Covid19  
count              48.000000  
mean                0.500000  
std                 0.505291  
min                 0.000000  
25%                 0.000000  
50%                 0.500000  
75%                 1.000000  
max                 1.000000

In [22]:
labels = np.array(df['Infected with Covid19'])
labels

array([0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1], dtype=int64)

In [54]:
feature = df.drop('Infected with Covid19', axis=1)
feature[:5]

Dry Cough  High Fever  Sore Throat  Difficulty in breathing
0          0           2            3                        0
1         15          15           20                       16
2          4           5            0                        0
3          4           7            9                       10
4          0           0            1                        0

In [55]:
feature = np.array(feature)
feature[:5]

array([[ 0,  2,  3,  0],
       [15, 15, 20, 16],
       [ 4,  5,  0,  0],
       [ 4,  7,  9, 10],
       [ 0,  0,  1,  0]], dtype=int64)

In [85]:
X_train, X_test, y_train, y_test = train_test_split(feature, labels, test_size=0.3, random_state=42)

In [86]:
print("Training data", X_train.shape)
print("Testing data",X_test.shape)

Training data (33, 4)
Testing data (15, 4)


In [113]:
rf = RandomForestRegressor(n_estimators=1000, random_state=10)

In [114]:
rf.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=1000,
                      n_jobs=None, oob_score=False, random_state=10, verbose=0,
                      warm_start=False)

In [115]:
prediction = rf.predict(X_test)
prediction

array([0.862, 0.   , 0.   , 0.   , 0.738, 0.815, 0.193, 0.884, 0.   ,
       0.442, 0.876, 0.189, 0.999, 0.862, 0.254])

In [116]:
print("Predicted data: ", prediction)
print("Actual data: ", y_test)

Predicted data:  [0.862 0.    0.    0.    0.738 0.815 0.193 0.884 0.    0.442 0.876 0.189
 0.999 0.862 0.254]
Actual data:  [1 0 0 0 0 1 0 1 0 1 1 0 1 1 0]


In [117]:
predictions = rf.predict([[15,15,20,16]])
predictions * 100

array([99.7])

In [118]:
import pickle

In [120]:
file = open('Models/RF48.pkl', 'wb')
pickle.dump(rf, file)
file.close()